version: "3"

networks:
  internal:

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:${POSTGRES_PORT}
    networks:
    - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 12
  pgmigrate:
    image: ghcr.io/peterldowns/pgmigrate:latest
    command: pgmigrate migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
    - internal
    volumes:
    - ./test/migrations:/migrations
    environment:
      PGM_MIGRATIONS: /migrations
      PGM_DATABASE: ${POSTGRES_CONN}
  service-match:
    build: .
    restart: unless-stopped
    # env_file: ./.env
    ports:
    - 8080:8080
    networks:
    - internal
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
