// Code generated by ogen, DO NOT EDIT.
package api

type CheckServerRes interface {
	checkServerRes()
}

type CreateBidRes interface {
	createBidRes()
}

type CreateTenderRes interface {
	createTenderRes()
}

type EditBidRes interface {
	editBidRes()
}

type EditTenderRes interface {
	editTenderRes()
}

type GetBidReviewsRes interface {
	getBidReviewsRes()
}

type GetBidStatusRes interface {
	getBidStatusRes()
}

type GetBidsForTenderRes interface {
	getBidsForTenderRes()
}

type GetTenderStatusRes interface {
	getTenderStatusRes()
}

type GetTendersRes interface {
	getTendersRes()
}

type GetUserBidsRes interface {
	getUserBidsRes()
}

type GetUserTendersRes interface {
	getUserTendersRes()
}

type RollbackBidRes interface {
	rollbackBidRes()
}

type RollbackTenderRes interface {
	rollbackTenderRes()
}

type SubmitBidDecisionRes interface {
	submitBidDecisionRes()
}

type SubmitBidFeedbackRes interface {
	submitBidFeedbackRes()
}

type UpdateBidStatusRes interface {
	updateBidStatusRes()
}

type UpdateTenderStatusRes interface {
	updateTenderStatusRes()
}
