// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *Bid) setDefaults() {
	{
		val := BidVersion(1)
		s.Version = val
	}
}

// setDefaults set default value of fields.
func (s *Tender) setDefaults() {
	{
		val := TenderVersion(1)
		s.Version = val
	}
}
